// Generated by scripts/update-predefined-variables.mjs. Do not edit manually.
// Source: https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md

export const generatedPredefinedVariables = [
  {
    "name": "Agent.BuildDirectory",
    "description": "The local path on the agent where all folders for a given build pipeline are created. This variable has the same value as `Pipeline.Workspace`. For example: `/home/vsts/work/1`. For more information about the agent directory structure, see Agent directory structure.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.ContainerMapping",
    "description": "A mapping from container resource names in YAML to their Docker IDs at runtime. Example follows table.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.Diagnostic",
    "description": "When `System.Debug` is set to `true`, an extra variable named `Agent.Diagnostic` is set to `true`. When `Agent.Diagnostic` is `true`, the agent collects more logs that can be used for troubleshooting network issues for self-hosted agents. For more information, see Network diagnostics for self-hosted agents.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#systemdebug"
  },
  {
    "name": "Agent.HomeDirectory",
    "description": "The directory the agent is installed into and contains the agent software. For example: `c:\\agent`. For more information about the agent directory structure, see Agent directory structure.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.Id",
    "description": "The ID of the agent.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.JobName",
    "description": "The name of the running job. The name is usually `Job` or `__default`, but in multi-config scenarios, it's the configuration.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.JobStatus",
    "description": "The status of the build. • `Canceled` • `Failed` • `Succeeded` • `SucceededWithIssues` (partially successful) • `Skipped` (last job) The environment variable should be referenced as `AGENT_JOBSTATUS`. The older `agent.jobstatus` is available for backwards compatibility.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.MachineName",
    "description": "The name of the machine on which the agent is installed.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.Name",
    "description": "The name of the agent that is registered with the pool. If you're using a self-hosted agent, then this value is the name you specify. See agents.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.OS",
    "description": "The operating system of the agent host. Valid values are: • `Windows_NT` • `Darwin` • `Linux` If you're running in a container, the agent host and container might be running different operating systems.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.OSArchitecture",
    "description": "The operating system processor architecture of the agent host. Valid values are: • `X86` • `X64` • `ARM`",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.TempDirectory",
    "description": "A temporary folder that is cleaned after each pipeline job. This directory is used by tasks such as .NET Core CLI task to hold temporary items like test results before they're published. For example: `/home/vsts/work/_temp` for Ubuntu.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.ToolsDirectory",
    "description": "The directory used by tasks such as Node Tool Installer and Use Python Version to switch between multiple versions of a tool. These tasks add tools from this directory to `PATH` so that subsequent build steps can use them. Learn about managing this directory on a self-hosted agent.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Agent.WorkFolder",
    "description": "The working directory for this agent. For example: `c:\\agent_work`. Note: This directory isn't guaranteed to be writable by pipeline tasks (for example, when mapped into a container). For more information about the agent directory structure, see Agent directory structure.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#agent-variables"
  },
  {
    "name": "Build.ArtifactStagingDirectory",
    "description": "The local path on the agent where any artifacts are copied to before being pushed to their destination. For example: `c:\\agent_work\\1\\a`. For more information about the agent directory structure, see Agent directory structure. A typical way to use this folder is to publish your build artifacts with the Copy files and Publish build artifacts tasks. Note: Build.ArtifactStagingDirectory and Build.StagingDirectory are interchangeable. This directory is purged before each new build, so you don't have to clean it up yourself. See Artifacts in Azure Pipelines. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.BinariesDirectory",
    "description": "The local path on the agent you can use as an output folder for compiled binaries. For example: `c:\\agent_work\\1\\b`. For more information about the agent directory structure, see Agent directory structure. By default, new build pipelines aren't set up to clean this directory. You can define your build to clean it up on the Repository tab. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.BuildId",
    "description": "The ID of the record for the completed build.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.BuildNumber",
    "description": "The name of the completed build, also known as the run number. You can specify what is included in this value. A typical use of this variable is to make it part of the label format, which you specify on the repository tab. Note: This value can contain whitespace or other invalid label characters. In these cases, the label format fails. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.BuildUri",
    "description": "The URI for the build. For example: `vstfs:///Build/Build/1430`. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Clean",
    "description": "This is a deprecated variable that modifies how the build agent cleans up source. To learn how to clean up source, see Clean the local repo on the agent.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#buildclean"
  },
  {
    "name": "Build.ContainerId",
    "description": "The ID of the container for your artifact. When you upload an artifact in your pipeline, it's added to a container that is specific for that particular artifact.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.CronSchedule.DisplayName",
    "description": "The `displayName` of the cron schedule that triggered the pipeline run. This variable is only set if a YAML scheduled trigger triggers the pipeline run. For more information, see schedules.cron definition - Build.CronSchedule.DisplayName variable. This variable is available in Azure DevOps Server 2022.1 and higher.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.DefinitionName",
    "description": "The name of the build pipeline. Note: This value can contain whitespace or other invalid label characters. In these cases, the label format fails.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.DefinitionVersion",
    "description": "The version of the build pipeline.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.QueuedBy",
    "description": "See How are the identity variables set?. Note: This value can contain whitespace or other invalid label characters. In these cases, the label format fails.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.QueuedById",
    "description": "See How are the identity variables set?.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Reason",
    "description": "The event that caused the build to run. • `Manual`: A user manually queued the build. • `IndividualCI`: **Continuous integration (CI)** triggered by a Git push or a TFVC check-in. • `BatchedCI`: **Continuous integration (CI)** triggered by a Git push or a TFVC check-in, and the **Batch changes** was selected. • `Schedule`: **Scheduled** trigger. • `ValidateShelveset`: A user manually queued the build of a specific TFVC shelveset. • `CheckInShelveset`: **Gated check-in** trigger. • `PullRequest`: A Git branch policy that requires a build triggers the build. • `BuildCompletion`: another build triggers the build • `ResourceTrigger`: A resource trigger or another build triggers the build. See Build pipeline triggers, Improve code quality with branch policies.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Clean",
    "description": "The value you select for **Clean** in the source repository settings. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Git.SubmoduleCheckout",
    "description": "The value you select for **Checkout submodules** on the repository tab. With multiple repos checked out, this value tracks the triggering repository's setting. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.ID",
    "description": "The unique identifier of the repository.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.LocalPath",
    "description": "The local path on the agent where your source code files are downloaded. For example: `c:\\agent_work\\1\\s`. By default, new build pipelines update only the changed files. You can modify how files are downloaded on the Repository tab. Important note: If you check out only one Git repository, this path is the exact path to the code. If you check out multiple repositories, the behavior is as follows (and might differ from the value of the Build.SourcesDirectory variable): • If the checkout step for the self (primary) repository has no custom checkout path defined, or the checkout path is the multi-checkout default path `$(Pipeline.Workspace)/s/<RepoName>` for the self repository, the value of this variable reverts to its default value, which is `$(Pipeline.Workspace)/s`. • If the checkout step for the self (primary) repository has a custom checkout path defined and it's not its multi-checkout default path, this variable contains the exact path to the self repository. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Name",
    "description": "The name of the triggering repository.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Provider",
    "description": "The type of the triggering repository. • `TfsGit`: TFS Git repository • `TfsVersionControl`: Team Foundation Version Control (TFVC) • `Git`: Git repository hosted on an external server • `GitHub` • `Svn`: Subversion It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Tfvc.Workspace",
    "description": "Defined if your repository is Team Foundation Version Control. The name of the TFVC workspace used by the build agent. For example, if the Agent.BuildDirectory is `c:\\agent_work\\12` and the Agent.Id is `8`, the workspace name could be: `ws_12_8`. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.Repository.Uri",
    "description": "The URL for the triggering repository. For example: • Git: https://fabrikamfiber@dev.azure.com/fabrikamfiber/_git/Scripts • TFVC: https://dev.azure.com/fabrikamfiber/ This variable can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.RequestedFor",
    "description": "See \"How are the identity variables set?\". Note: This value can contain whitespace or other invalid label characters. In these cases, the label format fails.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.RequestedForEmail",
    "description": "See \"How are the identity variables set?\".",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.RequestedForId",
    "description": "See \"How are the identity variables set?\".",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourceBranch",
    "description": "The branch of the triggering repo the build was queued for. Some examples: • Git repo branch: `refs/heads/main` • Git repo pull request: `refs/pull/1/merge` • TFVC repo branch: `$/teamproject/main` • TFVC repo gated check-in: `Gated_2016-06-06_05.20.51.4369;username@live.com` • TFVC repo shelveset build: `myshelveset;username@live.com` • When a tag triggers your pipeline: `refs/tags/your-tag-name` When you use this variable in your build number format, the forward slash characters (`/`) are replaced with underscore characters `_`). Note: In TFVC, if you're running a gated check-in build or manually building a shelveset, you can't use this variable in your build number format.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourceBranchName",
    "description": "The name of the branch in the triggering repo the build was queued for. • Git repo branch, pull request, or tag: The last path segment in the ref. For example, in `refs/heads/main`, this value is `main`. In `refs/heads/feature/tools`, this value is `tools`. In `refs/tags/your-tag-name`, this value is `your-tag-name`. • TFVC repo branch: The last path segment in the root server path for the workspace. For example, in `$/teamproject/main`, this value is `main`. • TFVC repo gated check-in or shelveset build is the name of the shelveset. For example, `Gated_2016-06-06_05.20.51.4369;username@live.com` or `myshelveset;username@live.com`. Note: In TFVC, if you're running a gated check-in build or manually building a shelveset, you can't use this variable in your build number format.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourcesDirectory",
    "description": "The local path on the agent where your source code files are downloaded. For example: `c:\\agent_work\\1\\s`. For more information about the agent directory structure, see Agent directory structure. By default, new build pipelines update only the changed files. Important note: If you check out only one Git repository, this path is the exact path to the code. If you check out multiple repositories, it reverts to its default value, which is `$(Pipeline.Workspace)/s`, even if the self (primary) repository is checked out to a custom path different from its multi-checkout default path `$(Pipeline.Workspace)/s/<RepoName>` (in this respect, the variable differs from the behavior of the Build.Repository.LocalPath variable). It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourceTfvcShelveset",
    "description": "Defined if your repository is Team Foundation Version Control. If you're running a gated build or a shelveset build, this variable is set to the name of the shelveset you're building. Note: This variable yields a value that is invalid for build use in a build number format.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourceVersion",
    "description": "The latest version control change of the triggering repo that is included in this build. • Git: The commit ID. • TFVC: the changeset. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.SourceVersionMessage",
    "description": "The comment of the commit or changeset for the triggering repo. We truncate the message to the first line or 200 characters, whichever is shorter. The `Build.SourceVersionMessage` corresponds to the message on `Build.SourceVersion` commit. The `Build.SourceVersion` commit for a PR build is the merge commit (not the commit on the source branch). It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. Also, this variable is only available on the step level. It isn't available in the job or stage levels. That is, the message isn't extracted until the job starts and the code is checked out. >Note: The **Build.SourceVersionMessage** variable doesn't work with classic build pipelines in Bitbucket repositories when **Batch changes while a build is in progress** is enabled.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.StageRequestedBy",
    "description": "The person who triggered the stage when the stage runs manually, or `Microsoft.VisualStudio.Services.TFS` otherwise. Note: This value can contain whitespace or other invalid label characters.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.StageRequestedForId",
    "description": "The GUID of identity of the person who triggered the stage when the stage runs manually, or `00000002-0000-8888-8000-000000000000` otherwise.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.StagingDirectory",
    "description": "The local path on the agent where any artifacts are copied to before being pushed to their destination. For example: `c:\\agent_work\\1\\a`. For more information about the agent directory structure, see Agent directory structure. A typical way to use this folder is to publish your build artifacts with the Copy files and Publish build artifacts tasks. Note: Build.ArtifactStagingDirectory and Build.StagingDirectory are interchangeable. This directory is purged before each new build, so you don't have to clean it up yourself. See Artifacts in Azure Pipelines. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.TriggeredBy.BuildId",
    "description": "If another build triggers the build, then this variable is set to the BuildID of the triggering build. In Classic pipelines, a build completion trigger triggers this variable. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. If you're triggering a YAML pipeline using `resources`, you should use the resources variables instead.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.TriggeredBy.BuildNumber",
    "description": "If another build triggers the build, then this variable is set to the number of the triggering build. In Classic pipelines, a build completion trigger triggers this variable. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. If you're triggering a YAML pipeline using `resources`, you should use the resources variables instead.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.TriggeredBy.DefinitionId",
    "description": "If another build triggers the build, then this variable is set to the DefinitionID of the triggering build. In Classic pipelines, a build completion trigger triggers this variable. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. If you're triggering a YAML pipeline using `resources`, you should use the resources variables instead.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.TriggeredBy.DefinitionName",
    "description": "If another build triggers the build, then this variable is set to the name of the triggering build pipeline. In Classic pipelines, a build completion trigger triggers this variable. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. If you're triggering a YAML pipeline using `resources`, you should use the resources variables instead.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Build.TriggeredBy.ProjectID",
    "description": "If another build triggers the build, then this variable is set to ID of the project that contains the triggering build. In Classic pipelines, a build completion trigger triggers this variable. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag. If you're triggering a YAML pipeline using `resources`, you should use the resources variables instead.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Checks.StageAttempt",
    "description": "Set to 1 the first time this stage is attempted, and increments every time the stage is retried. This variable can only be used within an approval or check for an environment. For example, you could use `$(Checks.StageAttempt)` within an Invoke REST API check.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#checks-variables"
  },
  {
    "name": "Common.TestResultsDirectory",
    "description": "The local path on the agent where the test results are created. For example: `c:\\agent_work\\1\\TestResults`. For more information about the agent directory structure, see Agent directory structure. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#build-variables"
  },
  {
    "name": "Environment.Id",
    "description": "ID of the environment targeted in the deployment job. For example, `10`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "Environment.Name",
    "description": "Name of the environment targeted in the deployment job to run the deployment steps and record the deployment history. For example, `smarthotel-dev`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "Environment.ResourceId",
    "description": "ID of the specific resource within the environment targeted in the deployment job to run the deployment steps. For example, `4`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "Environment.ResourceName",
    "description": "Name of the specific resource within the environment targeted in the deployment job to run the deployment steps and record the deployment history. For example, `bookings` which is a Kubernetes namespace that is added as a resource to the environment `smarthotel-dev`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "Pipeline.Workspace",
    "description": "Workspace directory for a particular pipeline. This variable has the same value as `Agent.BuildDirectory`. For example, `/home/vsts/work/1`. For more information about the agent directory structure, see Agent directory structure.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#pipeline-variables"
  },
  {
    "name": "Strategy.CycleName",
    "description": "The current cycle name in a deployment. Options are `PreIteration`, `Iteration`, or `PostIteration`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "Strategy.Name",
    "description": "The name of the deployment strategy: `canary`, `runOnce`, or `rolling`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#deployment-job-variables"
  },
  {
    "name": "System.AccessToken",
    "description": "Use the OAuth token to access the REST API. Use System.AccessToken from YAML scripts. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.CollectionId",
    "description": "The GUID of the Azure DevOps organization or collection.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.CollectionUri",
    "description": "The URI of the Azure DevOps organization or collection. For example: `https://dev.azure.com/fabrikamfiber/`.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.Debug",
    "description": "For more detailed logs to debug pipeline problems, define `System.Debug` and set it to `true`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#systemdebug"
  },
  {
    "name": "System.DefaultWorkingDirectory",
    "description": "The local path on the agent where your source code files are downloaded. For example: `c:\\agent_work\\1\\s` For more information about the agent directory structure, see Agent directory structure. On self-hosted agents, new build pipelines update only the changed files by default. You can modify how files are downloaded on the Repository tab. This variable is agent-scoped. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.DefinitionId",
    "description": "The ID of the build pipeline.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.HostType",
    "description": "Set to `build` if the pipeline is a build. For a release, the values are `deployment` for a Deployment group job, `gates` during evaluation of gates, and `release` for other (Agent and Agentless) jobs.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.JobAttempt",
    "description": "Set to 1 the first time this job is attempted, and increments every time the job is retried.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.JobDisplayName",
    "description": "The human-readable name given to a job.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.JobId",
    "description": "A unique identifier for a single attempt of a single job. The value is unique to the current pipeline.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.JobName",
    "description": "The name of the job, typically used for expressing dependencies and accessing output variables.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.OidcRequestUri",
    "description": "Generate an `idToken` for authentication with Entra ID using OpenID Connect (OIDC). Learn more.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PhaseAttempt",
    "description": "Set to 1 the first time this phase is attempted, and increments every time the job is retried. Note: *Phase* is a mostly redundant concept, which represents the design-time for a job (whereas job was the runtime version of a phase). The concept of phase is mostly removed from Azure Pipelines. Matrix and multi-config jobs are the only place where a phase is still distinct from a job. One phase can instantiate multiple jobs, which differ only in their inputs.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PhaseDisplayName",
    "description": "The human-readable name given to a phase.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PhaseName",
    "description": "A string-based identifier for a job, typically used for expressing dependencies and accessing output variables.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PlanId",
    "description": "A string-based identifier for a single pipeline run.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.IsFork",
    "description": "If the pull request is from a fork of the repository, this variable is set to `True`. Otherwise, it's set to `False`.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.PullRequestId",
    "description": "The ID of the pull request that caused this build. For example: `17`. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy).",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.PullRequestNumber",
    "description": "The number of the pull request that caused this build. This variable is populated for pull requests from GitHub that have a different pull request ID and pull request number. This variable is only available in a YAML pipeline if a branch policy affects the PR.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.SourceBranch",
    "description": "The branch that is being reviewed in a pull request. For example: `refs/heads/users/raisa/new-feature` for Azure Repos. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy). This variable is only available in a YAML pipeline if a branch policy affects the PR.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.SourceCommitId",
    "description": "The commit that is being reviewed in a pull request. (This variable is initialized only if the build ran because of a Git PR affected by a branch policy). This variable is only available in a YAML pipeline if a branch policy affects the PR.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.SourceRepositoryUri",
    "description": "The URL to the repo that contains the pull request. For example: `https://dev.azure.com/ouraccount/_git/OurProject`.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.TargetBranch",
    "description": "The branch that is the target of a pull request. For example: `refs/heads/main` when your repository is in Azure Repos and `main` when your repository is in GitHub. This variable is initialized only if the build ran because of a Git PR affected by a branch policy. This variable is only available in a YAML pipeline if a branch policy affects the PR.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.PullRequest.targetBranchName",
    "description": "The name of the target branch for a pull request. This variable can be used in a pipeline to conditionally execute tasks or steps based on the target branch of the pull request. For example, you might want to trigger a different set of tests or code analysis tools depending on the branch that the changes are being merged into.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.StageAttempt",
    "description": "Set to 1 the first time this stage is attempted, and increments every time the stage is retried.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.StageDisplayName",
    "description": "The human-readable name given to a stage.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.StageName",
    "description": "A string-based identifier for a stage, typically used for expressing dependencies and accessing output variables.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.TeamFoundationCollectionUri",
    "description": "The URI of the Azure DevOps organization or collection. For example: `https://dev.azure.com/fabrikamfiber/`. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.TeamProject",
    "description": "The name of the project that contains this build.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.TeamProjectId",
    "description": "The ID of the project that this build belongs to.",
    "availableInTemplates": true,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "System.TimelineId",
    "description": "A string-based identifier for the execution details and logs of a single pipeline run.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  },
  {
    "name": "TF_BUILD",
    "description": "Set to `True` if a build task runs the script. It can be used as an environment variable in a script and as a parameter in a build task. It can't be used as part of the build number or as a version control tag.",
    "availableInTemplates": false,
    "documentationUrl": "https://learn.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml&wt.mc_id=DT-MVP-5005372#system-variables"
  }
] as const;
